#ifndef MATCH20_H_GENERATED_
#define MATCH20_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

// 
// extern 
void WASM_RT_ADD_PREFIX(init)(void);
u32 wbg_self_e23d74ae45fb17d1(void){
    return 36;
}

u32 wbindgen_object_clone_ref(u32 p0i32){
    return p0i32 + 1;
};

u32 wbindgen_is_undefined(u32 p0i32){
    return 0;
}

u32 wbg_instanceof_Window_434ce1849eb4e0fc(u32 p0i32){
    return 1;
}

u32 wbg_document_5edd43643d1060d9(u32 p0i32){
    return p0i32 + 1;
};

u32 wbg_body_7538539844356c1c(u32 p0i32){
    return p0i32 + 1;
};

void wbindgen_object_drop_ref(u32 p0i32){

}

u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_instanceof_Window_434ce1849eb4e0fcZ_ii)(u32) = wbg_instanceof_Window_434ce1849eb4e0fc;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_document_5edd43643d1060d9Z_ii)(u32) = wbg_document_5edd43643d1060d9;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_body_7538539844356c1cZ_ii)(u32) = wbg_body_7538539844356c1c;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_newnoargs_f579424187aa1717Z_iii)(u32, u32) = NULL;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_call_89558c3e96703ca1Z_iii)(u32, u32) = NULL;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_globalThis_d61b1f48a57191aeZ_iv)(void) = NULL;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_self_e23d74ae45fb17d1Z_iv)(void) = wbg_self_e23d74ae45fb17d1;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_window_b4be7f48b24ac56eZ_iv)(void) = NULL;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_global_e7669da72fd7f239Z_iv)(void) = NULL;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbindgen_is_undefinedZ_ii)(u32) = wbindgen_is_undefined;
u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbindgen_object_clone_refZ_ii)(u32) = wbindgen_object_clone_ref;
void (*Z_Z2EZ2Findex_bgZ2EjsZ___wbindgen_object_drop_refZ_vi)(u32) = wbindgen_object_drop_ref;
void (*Z_Z2EZ2Findex_bgZ2EjsZ___wbindgen_throwZ_vii)(u32, u32) = NULL;



// /* import: './index_bg.js' '__wbg_instanceof_Window_434ce1849eb4e0fc' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_instanceof_Window_434ce1849eb4e0fcZ_ii)(u32);
// /* import: './index_bg.js' '__wbg_document_5edd43643d1060d9' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_document_5edd43643d1060d9Z_ii)(u32);
// /* import: './index_bg.js' '__wbg_body_7538539844356c1c' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_body_7538539844356c1cZ_ii)(u32);
// /* import: './index_bg.js' '__wbg_newnoargs_f579424187aa1717' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_newnoargs_f579424187aa1717Z_iii)(u32, u32);
// /* import: './index_bg.js' '__wbg_call_89558c3e96703ca1' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_call_89558c3e96703ca1Z_iii)(u32, u32);
// /* import: './index_bg.js' '__wbg_globalThis_d61b1f48a57191ae' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_globalThis_d61b1f48a57191aeZ_iv)(void);
// /* import: './index_bg.js' '__wbg_self_e23d74ae45fb17d1' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_self_e23d74ae45fb17d1Z_iv)(void);
// /* import: './index_bg.js' '__wbg_window_b4be7f48b24ac56e' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_window_b4be7f48b24ac56eZ_iv)(void);
// /* import: './index_bg.js' '__wbg_global_e7669da72fd7f239' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbg_global_e7669da72fd7f239Z_iv)(void);
// /* import: './index_bg.js' '__wbindgen_is_undefined' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbindgen_is_undefinedZ_ii)(u32);
// /* import: './index_bg.js' '__wbindgen_object_clone_ref' */
// extern u32 (*Z_Z2EZ2Findex_bgZ2EjsZ___wbindgen_object_clone_refZ_ii)(u32);
// /* import: './index_bg.js' '__wbindgen_object_drop_ref' */
// extern void (*Z_Z2EZ2Findex_bgZ2EjsZ___wbindgen_object_drop_refZ_vi)(u32);
// /* import: './index_bg.js' '__wbindgen_throw' */
// extern void (*Z_Z2EZ2Findex_bgZ2EjsZ___wbindgen_throwZ_vii)(u32, u32);

// /* export: 'memory' */
// extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
// /* export: 'sign' */
// extern void (*WASM_RT_ADD_PREFIX(Z_signZ_viii))(u32, u32, u32);
// /* export: '__wbindgen_add_to_stack_pointer' */
// extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_add_to_stack_pointerZ_ii))(u32);
// /* export: '__wbindgen_malloc' */
// extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_mallocZ_ii))(u32);
// /* export: '__wbindgen_realloc' */
// extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_reallocZ_iiii))(u32, u32, u32);
// /* export: '__wbindgen_free' */
// extern void (*WASM_RT_ADD_PREFIX(Z___wbindgen_freeZ_vii))(u32, u32);
// /* export: '__wbindgen_exn_store' */
// extern void (*WASM_RT_ADD_PREFIX(Z___wbindgen_exn_storeZ_vi))(u32);
// /* export: '__webpack_init__' */
// extern void (*WASM_RT_ADD_PREFIX(Z___webpack_init__Z_vv))(void);
#ifdef __cplusplus
}
#endif

#endif  /* MATCH20_H_GENERATED_ */
